// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkfadpqvubtfnfsvtkai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rZmFkcHF2dWJ0Zm5mc3Z0a2FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NjU0NzksImV4cCI6MjA1OTA0MTQ3OX0.cV08rLxC5S8jIlsQrLumHhmIJSg6e-igAVJ-HWG5KZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);